// Transcript fetcher — handles BOTH manual and auto-generated captions
// Auto-generated captions are available for MOST YouTube videos (80%+)
// The key is looking at the right caption tracks and falling back properly.

export async function fetchTranscript(videoId) {
  try {
    // Step 1: Get watch page
    const watchResp = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept-Language': 'en-US,en;q=0.9',
      },
    });

    if (!watchResp.ok) {
      return { videoId, segments: [], fullText: '', available: false, error: 'Failed to fetch watch page' };
    }

    const html = await watchResp.text();

    // Step 2: Extract player response
    let playerData = {};
    try {
      // Try multiple extraction patterns
      const patterns = [
        /ytInitialPlayerResponse\s*=\s*({.+?});/,
        /ytInitialPlayerResponse\s*=\s*({.+?})\s*;/,
        /var ytInitialPlayerResponse\s*=\s*({.+?});/,
      ];
      for (const p of patterns) {
        const m = html.match(p);
        if (m) { playerData = JSON.parse(m[1]); break; }
      }
    } catch (e) {
      console.error('[transcript] Failed to parse player data:', e.message);
    }

    // Step 3: Get caption tracks
    const captionsRenderer = (playerData.captions || {}).playerCaptionsTracklistRenderer || {};
    const captionTracks = captionsRenderer.captionTracks || [];

    if (captionTracks.length === 0) {
      return {
        videoId, segments: [], fullText: '', available: false,
        error: 'No captions available — this video has neither manual nor auto-generated captions enabled',
      };
    }

    // Step 4: Pick the best track
    // Priority: English manual > English auto > Any English > Any manual > Any auto
    let bestTrack =
      captionTracks.find(t => t.languageCode === 'en' && !(t.vssId || '').includes('a.')) ||  // English manual
      captionTracks.find(t => t.languageCode === 'en') ||                                      // English (any)
      captionTracks.find(t => !(t.vssId || '').includes('a.')) ||                              // Any manual
      captionTracks[0];                                                                         // Whatever's available

    // Step 5: Fetch caption XML
    const captionUrl = bestTrack.baseUrl;
    if (!captionUrl) {
      return { videoId, segments: [], fullText: '', available: false, error: 'No caption URL found' };
    }

    const captionResp = await fetch(captionUrl, {
      headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36' },
    });

    if (!captionResp.ok) {
      return { videoId, segments: [], fullText: '', available: false, error: 'Failed to fetch caption data from YouTube' };
    }

    const captionXml = await captionResp.text();

    // Step 6: Parse XML into segments
    const segments = parseCaptionXml(captionXml);

    const fullText = segments.map(s => s.text).join(' ');
    const isAuto = (bestTrack.vssId || '').includes('a.');

    return {
      videoId,
      segments,
      fullText,
      available: segments.length > 0,
      isAutoGenerated: isAuto,
      trackName: bestTrack.name?.simpleText || (isAuto ? 'Auto-generated' : 'Manual'),
      language: bestTrack.languageCode || 'en',
      error: segments.length === 0 ? 'Parsed 0 segments from caption data' : undefined,
    };
  } catch (err) {
    return { videoId, segments: [], fullText: '', available: false, error: err.message || 'Transcript fetch failed' };
  }
}

function parseCaptionXml(xml) {
  const segments = [];

  // Format 1: <text start="..." dur="...">content</text>
  let regex = /<text\s+start="([^"]+)"\s+dur="([^"]+)"[^>]*>([\s\S]*?)<\/text>/g;
  let match;
  while ((match = regex.exec(xml)) !== null) {
    const text = cleanCaptionText(match[3]);
    if (text) {
      segments.push({ text, start: parseFloat(match[1]), duration: parseFloat(match[2]) });
    }
  }

  // Format 2: <text start="...">content</text> (no dur)
  if (segments.length === 0) {
    regex = /<text\s+start="([^"]+)"[^>]*>([\s\S]*?)<\/text>/g;
    while ((match = regex.exec(xml)) !== null) {
      const text = cleanCaptionText(match[2]);
      if (text) {
        segments.push({ text, start: parseFloat(match[1]), duration: 0 });
      }
    }
  }

  // Format 3: <p t="..." d="...">content</p> (some formats use <p>)
  if (segments.length === 0) {
    regex = /<p\s+t="([^"]+)"\s+d="([^"]+)"[^>]*>([\s\S]*?)<\/p>/g;
    while ((match = regex.exec(xml)) !== null) {
      const text = cleanCaptionText(match[3]);
      if (text) {
        segments.push({ text, start: parseFloat(match[1]) / 1000, duration: parseFloat(match[2]) / 1000 });
      }
    }
  }

  // Merge very short segments (auto-captions often produce fragments)
  if (segments.length > 0) {
    const merged = [segments[0]];
    for (let i = 1; i < segments.length; i++) {
      const prev = merged[merged.length - 1];
      const curr = segments[i];
      // Merge if previous segment is very short (< 1 sec) and same sentence
      if (prev.duration < 1 && !prev.text.match(/[.!?]$/) && curr.start - (prev.start + prev.duration) < 0.5) {
        prev.text += ' ' + curr.text;
        prev.duration = (curr.start + curr.duration) - prev.start;
      } else {
        merged.push(curr);
      }
    }
    return merged;
  }

  return segments;
}

function cleanCaptionText(raw) {
  return raw
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(code))
    .replace(/<[^>]+>/g, '')   // strip HTML tags
    .replace(/\n/g, ' ')
    .replace(/\[.*?\]/g, '')   // strip [Music], [Laughter] etc
    .trim();
}
